apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifact-cache.fullname" . }}
  labels:
    {{- include "artifact-cache.labels" . | nindent 4 }}
  {{- $ambassadorId := .Values.ambassador.ambassador_id }}
  {{- if and (not $ambassadorId) (hasKey .Values "global") (hasKey .Values.global "ambassador_id") }}
  {{- $ambassadorId = .Values.global.ambassador_id }}
  {{- end }}
  {{- if or .Values.ambassador.flag .Values.service.annotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ambassador.flag }}
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  {{ .Values.ambassador.mapping_name }}
      prefix: /artifact/
      service: {{ include "artifact-cache.fullname" . }}:{{ .Values.service.port }}
      {{- if $ambassadorId }}
      ambassador_id: {{ $ambassadorId }}
      {{- end }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "artifact-cache.selectorLabels" . | nindent 4 }}